### ISSUE TITLE
Email the 'Services' mailing list and ask them to opt in to main newsletter

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/internal#28]
Related to #25 
This was put forward as a suggestion yesterday, so let's discuss it before implementing.

The[ Services email list](https://us9.admin.mailchimp.com/lists/members/?id=426793) contains 613 contacts.

It is quite elderly now and it was gathered in large part by getting addresses form attendees of our Data Breakfasts. While there were some council attendees, there were also people from the kinds of organisations we then thought we might work with - eg ORR, Channel 4 etc.

In this scenario, we send the list an invitation to sign up to the main mySociety newsletter, including checkboxes that allow users to self-select the segmented news they would like, ie, Better Cities, Journalism, Campaigning, etc.

cc / @jukesie @markcridge

**Comment by abimysoc** [comment]
I think we should do this and am assigning @MyfanwyNixon to do it. We shouldn't be hanging on to people's data if we're not using it (bad data protection practice, plus Mailchimp lists cost us money) so I'm also setting a deadline: this needs to be done before Christmas because I'm going to delete the list when I come back to work in January.

**Comment by MyfanwyNixon** [comment]
- [x] People already on both lists - removed from Services list
- [x] Mail sent to remaining folk
- [ ] Will send follow-up mail in 1 week to anyone who hasn't opened the first one
- [ ] Will delete list 7 days after that (Mailchimp doesn't allow you to delete a list earlier than that)

**Comment by abimysoc** [comment]
Done.
