### ISSUE TITLE
Bots too verbose

### ISSUE THREAD

**Issue by dracos** [mysociety/internal#38]
e.g. the standup bot is emailing wiki on leopard every minute to say it is doing nothing; the randomiser doesn't need to email what page it's picked every day. A bot should only output stuff by email if there is an issue that needs looking at (and ideally, that email should be sent to someone to look at, not dumped in a mailbox).

**Comment by jacksonj04** [comment]
To do:

* [x] Make the bots shut up unless there's something to tell people (Fixed in #40)
* [ ] Create a new `cron-bots` email address so that error reports have somewhere to go. Add interested people to it.
* [ ] Add a `MAILTO=` to the `crontab.ugly` for the new email address, so error reports don't just loiter in `wiki`'s mailbox for all eternity.
