### ISSUE TITLE
a manual mechanism for making a project ("deal") wiki page

### ISSUE THREAD

**Issue by davewhiteland** [mysociety/internal#7]
Note: using the horrible and wrong word "deal" here because that's the unchangeable Pipedrive terminology.

Some deals (in international) can represent a lot of work and effort (correspondence, meetings, visits, fundraising) long before the installation exists, i.e., before they can be represented in projectDB. So it's reasonable to have them represented in the wiki (in fact it's almost unthinkable that they shoudn't be linking to other things in the wiki by that stage).  So there is a case for being able to generate a page for a "deal" from Pipedrive (i.e., naming convention and infobox with backlinks to Pipedrive). I also think this isn't the case for most deals, which can happily be stored in Pipedrive, which is why I suggest a way to manually autocreate such pages rather than an overnight catch-them-all sweep (which works for Organisations).

I don't _think_ that every project is necessarily the same thing as it's subsequent installation, although I suspect many of them are. So this does feel like it's representing and storing information about a Real Thing that is not the same as the other wiki pages we currently generate relating to that thing.

**Comment by abimysoc** [comment]
I think we're part way towards this in ProjectDB now, because the ability now exists to represent a 'project' independently of an 'install' (and then when a website comes into existence you can create the install and link it back to the project). The little bot pootles around making wiki pages for installs, but it doesn't yet do it for projects AFAIK.
